{
 "title": "Request / Trace Explorer",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Opentelemetry tracing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "service": "otel_service1" }
   ]
  },
  {
   "title": "Opentelemetry service1 duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "limit": 20, "serviceName": "otel_service1" }
   ]
  },
  {
   "title": "Structured logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1|service2` | line_format `{{ .asctime }} | {{ .name }} | {{ .message }} | {{ .request_id }}`"
    }
   ]
  },
  {
   "title": "Total Duration - Structured logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"complete\""
    }
   ]
  },
  {
   "title": "Total Duration - Structured logs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"complete\""
    }
   ]
  },
  {
   "title": "Duration - Structured logs - Service 1 duration",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"proxy\" "
    }
   ]
  },
  {
   "title": "Duration - Structured logs - Service 1 duration over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"proxy\" "
    }
   ]
  },
  {
   "title": "Duration - Structured logs - Service 1 duration",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service1` |~ \"proxy\" "
    }
   ]
  },
  {
   "title": "Duration - Structured logs - Service 2 duration",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"complete\""
    }
   ]
  },
  {
   "title": "Duration - Structured logs - Service 2 duration over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"complete\""
    }
   ]
  },
  {
   "title": "Duration - Structured logs - Service 2 duration",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"start\""
    },
    {
     "expr": "{job=\"docker\"} | json | name =~ `service2` |~ \"complete\""
    }
   ]
  }
 ]
}